allowBuilds:
  "@reown/appkit": true
  bufferutil: true
  esbuild: true
  keccak: true
  sharp: false
  unrs-resolver: false
  utf-8-validate: true
overrides:
  axios: 1.19.0
  ws: 8.21.0
patchedDependencies:
  '@privy-io/react-auth@3.37.1': patches/@privy-io__react-auth@3.37.1.patch
