import type { Metadata } from "next";

import { CreateWarehouseForm } from "@/components/warehouses/create-warehouse-form";

export const metadata: Metadata = {
  title: "Create Warehouse",
  description: "Create a new Chainventory warehouse.",
  robots: { index: false, follow: false },
};

/**
 * Create Warehouse (PRD §6.2, DESIGN §27–28): form (name, company, type) +
 * deployment progress on-chain. Warehouse code & contract address are
 * auto-generated by the server.
 */
export default function CreateWarehousePage() {
  return <CreateWarehouseForm />;
}
