import type { Metadata } from "next";

import { CreateWarehouseForm } from "@/components/warehouses/create-warehouse-form";
import {
  redirectIfOwnsActiveWarehouse,
  requireOnboardingUser,
} from "@/lib/onboarding/guard";

export const metadata: Metadata = {
  title: "Create Warehouse",
  description: "Create a new Chainventory warehouse.",
  robots: { index: false, follow: false },
};

/**
 * Create Warehouse (PRD §6.2, DESIGN §27–28): form (name, company, type) +
 * deployment progress on-chain. Warehouse code & contract address are
 * auto-generated by the server.
 */
export const dynamic = "force-dynamic";

export default async function CreateWarehousePage() {
  // FE-02: belum login → /login?next=...; sudah own warehouse aktif →
  // /dashboard (create pasti 409 — cegah sebelum user sign).
  const { supabase, user } =
    await requireOnboardingUser("/onboarding/create");
  await redirectIfOwnsActiveWarehouse(supabase, user.id);
  return <CreateWarehouseForm />;
}
