import type { Metadata } from "next";

import { AuthShell } from "@/components/auth/auth-shell";
import { AuthUnavailableState } from "@/components/auth/auth-unavailable-state";
import { APP_NAME } from "@/lib/constants";
import { getLocale } from "@/lib/i18n/server";
import { translate } from "@/lib/i18n/translations";
import { CreateWarehouseForm } from "@/components/warehouses/create-warehouse-form";
import {
  redirectIfOwnsActiveWarehouse,
  requireOnboardingUser,
} from "@/lib/onboarding/guard";

export const metadata: Metadata = {
  title: "Create Warehouse",
  description: "Create a new Chainventory warehouse.",
  robots: { index: false, follow: false },
};

/**
 * Create Warehouse (PRD §6.2, DESIGN §27–28): form (name, company, type) +
 * deployment progress on-chain. Warehouse code & contract address are
 * auto-generated by the server.
 */
export const dynamic = "force-dynamic";

export default async function CreateWarehousePage() {
  // FE-02: belum login → /login?next=...; sudah own warehouse aktif →
  // /dashboard (create pasti 409 — cegah sebelum user sign).
  const auth = await requireOnboardingUser("/onboarding/create");
  const locale = await getLocale();
  const t = (key: string, params?: Record<string, string>) =>
    translate(locale, key, params);
  const shellLabels = {
    homeLabel: t("brand.home_aria", { app: APP_NAME }),
    skipLabel: t("auth.skip_auth_form"),
    backLabel: t("auth.back_home"),
  };
  if (auth.authUnavailable) {
    return (
      <AuthShell wide {...shellLabels}>
        <AuthUnavailableState />
      </AuthShell>
    );
  }
  await redirectIfOwnsActiveWarehouse(auth.supabase, auth.user.id);
  return (
    <AuthShell wide {...shellLabels}>
      <CreateWarehouseForm />
    </AuthShell>
  );
}
